### ISSUE TITLE
read_lines() should treat bare \r as a newline

### ISSUE THREAD

**Issue by hadley** [r-lib/brio#4]
For compatibility with `readLines()`

**Comment by jimhester** [comment]
er, are you sure, that is pretty weird behavior...

**Comment by hadley** [comment]
Yeah, but it's what base R does. @gaborcsardi had some thoughts too.

**Comment by gaborcsardi** [comment]
Yeah, I also think it should. I am pretty sure `readLines()` does it to be compatible with old Macintosh systems which use `\r` for the end of line character. Which is not super important any more, but I also don't see a good reason not to be compatible with `readLines()`.

**Comment by jimhester** [comment]
Part of the point of brio is to _not_ do these implicit conversions that readLines does though. I don't think it is generally useful and can be actively harmful if you are trying to preserve the unchanged output of a things like a progress bar or similar to a file.

**Comment by jimhester** [comment]
Particularly in the file snapshotting case I think is would be much better to keep the `\r` as is, otherwise how do you disambiguate things like this.

```r
cat("foo\nbar\n")
```

```r
cat("foo\rbar\n")
```

They do not do the same thing when printed interactively, and it seems to me better that when output to a file they have different binary representations.

**Comment by gaborcsardi** [comment]
Right, but you can use `read_file()` for that. In general that is better if you want to preserve a bunch of output "as is".

**Comment by gaborcsardi** [comment]
I think for the snapshot output, ideally you would want to compare the `\r` characters as well, to check equality, but then when you print the diff, you want to break at the `\r` as well, because otherwise you'd get long lines to compare, potentially, if a progress bar was updated lots of times.

Short of this ideal solution, it seems better to break at `\r` as well.

**Comment by jimhester** [comment]
More concretely doing this would basically require rewriting the inner loop of the read_lines function completely. We would have to change from using `strchr()` to `strpbrk()` and also complicate the implementation because when we reach a '\r' I would need to peek at the next byte of the file to see if it was a '\n' (and should be ignored). And because we are using buffered reads and this byte could be on the break between buffers getting the condition correct is not entirely trivial.

**Comment by hadley** [comment]
Ok, if you think it's going to be a lot of work, and not a great idea, then I'll think about a different approach for testthat, and we can revisit this issue if another case where breaking on `\r` comes up in the future.
